name: open_exchange_rates
description: A dartlang wrapping for openexchangerates api requests. Make api easy to use.
version: 1.0.0
author: Chuan-Yen Chiang <cychiang0823@gmail.com>
homepage: https://github.com/cychiang/open_exchange_rates
environment:
  sdk: '>=2.0.0-dev.55.0 <3.0.0'
dependencies:
  http: '^0.11.3+17'
  uri: '^0.11.3'
