name: open_exchange_rates
description: A dartlang wrapping for openexchangerates api requests.
version: 0.0.2
author: Casper CY Chiang <cychiang0823@gmail.com>
homepage: https://github.com/cychiang/open_exchange_rates
environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'
dependencies:
  http: '^0.11.3+16'
  uri: '^0.11.2'
  rxdart: '^0.18.0'
