name: open_exchange_rates
description: A library for Open Exchange Rates API to make it easy to use and get data from the API right away.
version: 1.0.0
homepage: https://github.com/cychiang/open_exchange_rates
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.2
  intl: ^0.16.1
  json_annotation: ^3.0.0
  uri: ^0.11.3+1

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  mock_web_server: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.14.4
